# This file is automatically generated by 'gen-command' command in Makefile.
# Don't edit this file manually.
# Run the module's apis.

preprocessing-match_masks_image:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/preprocessing/match_masks_image.py

preprocessing-mask_profile:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/preprocessing/mask_profile.py

preprocessing-mask_schema:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/preprocessing/mask_schema.py

preprocessing-resampling_segmentation_bulk:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/preprocessing/resampling_segmentation_bulk.py

preprocessing-resampling:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/preprocessing/resampling.py

preprocessing-resampling_segmentation_bulk_multiprocessing:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/preprocessing/resampling_segmentation_bulk_multiprocessing.py

plot-plot2d_masks:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/plot/plot2d_masks.py

plot-plot2d_layered_image_mask:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/plot/plot2d_layered_image_mask.py

plot-plot3d_images:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/plot/plot3d_images.py

plot-plot3d_masks:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/plot/plot3d_masks.py

plot-plot2d_images:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/plot/plot2d_images.py

plot-plot2Dfrom3DMostVlueMask:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/plot/plot2Dfrom3DMostVlueMask.py

collage-collage3d:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/collage/collage3d.py

collage-collage3d_2dslice:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/collage/collage3d_2dslice.py

collage-collage2d_stats:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/collage/collage2d_stats.py

utils-profile:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/utils/profile.py

utils-mask-zero_out:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/utils/mask/zero_out.py

features-collage3d:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/features/collage3d.py

features-collage2d:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python api/features/collage2d.py
