# This file is automatically generated by 'gen-command' command in Makefile.
# Don't edit this file manually.
# Run the module's apis.

plot_image_examples:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python api/plot_image_examples.py

utility:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python api/utility.py

layered_plot_examples:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python api/layered_plot_examples.py

layered_plot2D_examples:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python api/layered_plot2D_examples.py

generate_gif:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python api/generate_gif.py

plot_image_masks:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python api/plot_image_masks.py

gif_example:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python api/gif_example.py
