# This file is automatically generated by 'gen-command' command in Makefile.
# Don't edit this file manually.
# Run the module's scripts.

blowup_limited:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/blowup_limited.py

blowup:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/blowup.py

exatest:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/exatest.py

bowel_plot_overlap_expand_removeback:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/bowel_plot_overlap_expand_removeback.py

nifti_preprocessing:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/nifti_preprocessing.py

bowel_plot_overlap:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/bowel_plot_overlap.py

find_overlap:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/find_overlap.py

__init__:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/__init__.py

mask_preprocessing_to_binary:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/mask_preprocessing_to_binary.py

utility-log:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/utility/log.py

utility-reader:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/utility/reader.py

utility-utility:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/utility/utility.py

utility-__init__:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/utility/__init__.py

utility-helper_plot:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/utility/helper_plot.py

utility-arr:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/utility/arr.py

utility-custom_type:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/utility/custom_type.py

utility-helper_mask:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/utility/helper_mask.py

nifiti_helper:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/nifiti_helper.py

plots-gif:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/plots/gif.py

plots-plot_images:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/plots/plot_images.py

plots-layered_plot2D:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/plots/layered_plot2D.py

plots-plot_image:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/plots/plot_image.py

plots-layered_plot:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/plots/layered_plot.py

mask_preprocessing:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/mask_preprocessing.py

blowupscroll:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/blowupscroll.py

bowel_plot_overlap_expand:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/bowel_plot_overlap_expand.py

example:
		/media/storage/github/mohsen2/medviz/env_fes-local_linux_3.11/bin/python medviz/example.py
