### THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT THIS FILE DIRECTLY ###
export QT_QPA_PLATFORM := wayland

unittest:
		$(PY) -m unittest $(SRC)/test_*.py

plots-helper_plot:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/helper_plot.py

plots-plot2d-image_masks:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/plot2d/image_masks.py

plots-plot2d-__init__:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/plot2d/__init__.py

plots-plot2d-image_mask_annotated:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/plot2d/image_mask_annotated.py

plots-plot2d-masks:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/plot2d/masks.py

plots-plot2d-images:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/plot2d/images.py

plots-plot3d-__init__:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/plot3d/__init__.py

plots-plot3d-masks:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/plot3d/masks.py

plots-plot3d-images:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/plot3d/images.py

plots-plot3d-layered_plot:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/plot3d/layered_plot.py

plots-layered_plot2D:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/layered_plot2D.py

plots-__init__:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/__init__.py

plots-_plot_image:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/_plot_image.py

plots-gif:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/plots/gif.py

preprocess-mask:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/preprocess/mask.py

preprocess-__init__:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/preprocess/__init__.py

preprocess-match_image_mask:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/preprocess/match_image_mask.py

preprocess-resampling:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/preprocess/resampling.py

utils-helper_path:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/utils/helper_path.py

utils-array_threshold:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/utils/array_threshold.py

utils-__init__:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/utils/__init__.py

utils-helper_mask:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/utils/helper_mask.py

utils-log:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/utils/log.py

utils-utility:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/utils/utility.py

utils-reader:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/utils/reader.py

utils-custom_type:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/utils/custom_type.py

utils-array_profile:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/utils/array_profile.py

__init__:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/__init__.py

multimodal-stats:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/multimodal/stats.py

multimodal-__init__:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/multimodal/__init__.py

multimodal-save_dicom_metadata:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/multimodal/save_dicom_metadata.py

feats-collage-collage3d:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/feats/collage/collage3d.py

feats-collage-stats:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/feats/collage/stats.py

feats-collage-__init__:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/feats/collage/__init__.py

feats-collage-main:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/feats/collage/main.py

feats-collage-collage2d:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/feats/collage/collage2d.py

feats-collage-compute_collage:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/feats/collage/compute_collage.py

feats-__init__:
		/home/mohsen/envs/github/medviz/env_home_linux_3.11/bin/python medviz/feats/__init__.py
