# This file is automatically generated by 'gen-command' command in Makefile.
# Don't edit this file manually.
export QT_QPA_PLATFORM := wayland

__init__:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/__init__.py

preprocess-__init__:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/preprocess/__init__.py

preprocess-match_image_mask:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/preprocess/match_image_mask.py

preprocess-mask:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/preprocess/mask.py

utils-log:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/utils/log.py

utils-reader:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/utils/reader.py

utils-array_profile:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/utils/array_profile.py

utils-utility:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/utils/utility.py

utils-__init__:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/utils/__init__.py

utils-custom_type:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/utils/custom_type.py

utils-helper_mask:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/utils/helper_mask.py

utils-array_threshold:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/utils/array_threshold.py

plots-plot2d-__init__:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/plot2d/__init__.py

plots-plot2d-images:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/plot2d/images.py

plots-plot2d-image_masks:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/plot2d/image_masks.py

plots-gif:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/gif.py

plots-layered_plot2D:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/layered_plot2D.py

plots-__init__:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/__init__.py

plots-helper_plot:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/helper_plot.py

plots-_plot_image:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/_plot_image.py

plots-plot3d-__init__:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/plot3d/__init__.py

plots-plot3d-images:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/plot3d/images.py

plots-plot3d-layered_plot:
		/media/storage/github/mohsen2/medviz/env_home_linux_3.11/bin/python medviz/plots/plot3d/layered_plot.py
